[package]
name = "my_thread_pool"
version = "0.0.0"
authors = ["Dmitry Rodionov <gh@rdmtr.com>"]
include = ["src"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
